### ISSUE TITLE
budgetbutlerweb-companion-frontend-static startet nicht

### ISSUE THREAD

**Issue by BitNike** [SebastianRzk/BudgetButlerWeb#280]
Hi, 
ich habe das Problem, dass der Container budgetbutlerweb-companion-frontend-static nicht startet. Der Rest steht auf running und healthy.

Die logs sehen wie folgt aus: 
```
udgetbutlerweb_companion_cron    | checkup finished
budgetbutlerweb_companion_api     | [2025-03-28T14:33:34Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 201 2 "-" "curl/7.88.1" 0.000044
budgetbutlerweb_companion_api     | [2025-03-28T14:33:46Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 201 2 "-" "curl/7.88.1" 0.000048
budgetbutlerweb_companion_api     | [2025-03-28T14:33:58Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 201 2 "-" "curl/7.88.1" 0.000039
budget_butler_static              | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
budget_butler_static              | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
budget_butler_static              | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
budget_butler_static              | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
budget_butler_static              | /docker-entrypoint.sh: Configuration complete; ready for start up
budget_butler_static              | 2025/03/28 14:34:01 [emerg] 1#1: host not found in upstream "budget-butler-api" in /etc/nginx/conf.d/default.conf:16
budget_butler_static              | nginx: [emerg] host not found in upstream "budget-butler-api" in /etc/nginx/conf.d/default.conf:16
budget_butler_static exited with code 1
budgetbutlerweb_companion_api     | [2025-03-28T14:34:10Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 201 2 "-" "curl/7.88.1" 0.000047
budgetbutlerweb_companion_api     | [2025-03-28T14:34:22Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 201 2 "-" "curl/7.88.1" 0.000038
```

Wenn ich das richtig sehe, liegt es an den Einstellungen in der api.env Datei. 

Zu meinem Setup: 
Der BudgetButler soll nur bei mir im Heimnetzwerk laufen. Die ClientID und Secret habe ich über authentik erstellt (auch im lokalem Netzwerk installiert und per http erreichbar). 

```
# Zum Beispiel: mysql://username:password@docker-container-name:3306/butler
DATABASE_URL=mysql://butler:butler@db/butler

# Die Domain, unter welcher die Anwendung erreichbar ist (f  r OpenID Connect Redirects)
HOSTNAME=http://192.168.2.47:9000

# ClientId + ClientSecret + Issuer-Url vom OpenId Provider, zum Beispiel Authentik oder Keycloak
CLIENT_ID=J01hQqf0airMkPyqesbHNDeibzOO3aHAr2oOnOWt
CLIENT_SECRET=xLtXsHpPgylszlXzB9ZvCJuZUB8NUnCsjNOeBmvDjGcrUEeNds8L2VadV8T3oVVaR2hOUu84IK8Y1kZjE3cdNQXQss1YLNxiQSIQHrHsAMcAoeSIG0IKUxaFb3HErp7c
ISSUER=http://192.168.2.47:9000/application/o/budgetbutler/

# Kommaseparierte Liste von erlaubten Redirect-Urls. Wenn die Desktop-App auf einem anderen Port l  uft oder im Netzwerk
# erreichbar ist, muss die URL hier eingetragen werden.
# Beispiel: http://localhost:5000,http://my.local.url
# An sonsten einfach nicht konfigurieren, dann wird der Standardwert http://localhost:5000 verwendet f  r die normale Desktop-App
#ALLOWED_REDIRECTS=
```

Hast du ne Idee wieso es bei mir nicht läuft? 

Ich danke dir schon mal. 

VG
Sascha

**Comment by SebastianRzk** [comment]
Hallo Sasha,

Danke für deinen Bug-Report und ebenfalls danke, dass du dich an meinem docker-compose Beispiel  orientiert hast.

Leider hat sich bei dem Beispiel ein Fehler eingeschlichen. Der "static" container sollte im Netzwerk "butler-internal" sein (wie beim docker-compose.yml mit lokalem build.

Dann funktioniert es bei mir wieder 🥳

Funktioniert dann es bei dir auch?

(Das Beispiel werde ich asap anpassen)

**Comment by SebastianRzk** [comment]
Was mir bei der API configuration noch auffällt:

Authentik und die Begleiter-App laufen auf gleicher IP und Port. Wahrscheinlich ist das nicht korrekt, oder?

**Comment by BitNike** [comment]
Hi, Danke für deine schnelle Rückmeldung. 

Habe heute den Vormittag da dran verbracht und bin ein bisschen verzweifelt. Es wollte einfach nicht starten. 

Ich nutze Proxmox und habe in einem Container einige Docker Container am laufen. Aus dem Grund habe ich deinen Port von 80:80 auf 899 geändert. 

Mit Authentik habe ich heute das erste mal gearbeitet. Bin mir auch nicht sicher ob da alles richtig eingestellt ist. Kann man den dein Budget Butler auch ohne Authentik nutzen? Im Heimnetz ist das für mich uninteressant. 

Dies war mein Docker-Compose File. Ich habe nur den container_name hinzu gefügt, den Port geändert und den mich an den Docker Hub Images bedient. 
```
version: '3'
services:
  budget-butler-static:
    container_name: budget_butler_static
    image: sebastianrzk/budgetbutlerweb-companion-frontend-static:latest
    ports:
      - "899:80"
    restart: unless-stopped
  budget-butler-api:
    container_name: budgetbutlerweb_companion_api
    image: sebastianrzk/budgetbutlerweb-companion-api:latest
    env_file:
      - api.env
    restart: unless-stopped
    networks:
      - butler-internal
      - butler-db
  budget-butler-cron:
    container_name: budgetbutlerweb_companion_cron
    image: sebastianrzk/budgetbutlerweb-companion-cron:latest
    env_file:
      - api.env
    restart: unless-stopped
    networks:
      - butler-db
  db:
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env
    command: --max_allowed_packet=134217728
    restart: unless-stopped
    networks:
      - butler-db

volumes:
  db:
networks:
  butler-internal:
  butler-db:
```

Ich hoffe ich komme morgen dazu es noch mal zu probieren. Finde dein Projekt interessant.

**Comment by SebastianRzk** [comment]
Hej :)

kein Thema. Ich habe die Doku soweit aktualisiert.

So sollte deine aktualisierte `docker-compose.yml` aussehen:

```
version: '3'
services:
  budget-butler-static:
    container_name: budget_butler_static
    image: sebastianrzk/budgetbutlerweb-companion-frontend-static:latest
    ports:
      - "899:80"
    restart: unless-stopped
    networks:
      butler-internal:
  budget-butler-api:
    container_name: budgetbutlerweb_companion_api
    image: sebastianrzk/budgetbutlerweb-companion-api:latest
    env_file:
      - api.env
    restart: unless-stopped
    networks:
      - butler-internal
      - butler-db
  budget-butler-cron:
    container_name: budgetbutlerweb_companion_cron
    image: sebastianrzk/budgetbutlerweb-companion-cron:latest
    env_file:
      - api.env
    restart: unless-stopped
    networks:
      - butler-db
  db:
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env
    command: --max_allowed_packet=134217728
    restart: unless-stopped
    networks:
      - butler-db

volumes:
  db:
networks:
  butler-internal:
  butler-db:

```

In deiner `api.env` sollte dann noch der neue Port hinterlegt sein:

```
# Zum Beispiel: mysql://username:password@docker-container-name:3306/butler
DATABASE_URL=mysql://butler:butler@db/butler

# Die Domain, unter welcher die Anwendung erreichbar ist (f  r OpenID Connect Redirects)
HOSTNAME=http://192.168.2.47:899

# ClientId + ClientSecret + Issuer-Url vom OpenId Provider, zum Beispiel Authentik oder Keycloak
CLIENT_ID=J01hQqf0airMkPyqesbHNDeibzOO3aHAr2oOnOWt
CLIENT_SECRET=xLtXsHpPgylszlXzB9ZvCJuZUB8NUnCsjNOeBmvDjGcrUEeNds8L2VadV8T3oVVaR2hOUu84IK8Y1kZjE3cdNQXQss1YLNxiQSIQHrHsAMcAoeSIG0IKUxaFb3HErp7c
ISSUER=http://192.168.2.47:9000/application/o/budgetbutler/

# Kommaseparierte Liste von erlaubten Redirect-Urls. Wenn die Desktop-App auf einem anderen Port l  uft oder im Netzwerk
# erreichbar ist, muss die URL hier eingetragen werden.
# Beispiel: http://localhost:5000,http://my.local.url
# An sonsten einfach nicht konfigurieren, dann wird der Standardwert http://localhost:5000 verwendet f  r die normale Desktop-App
#ALLOWED_REDIRECTS=
```

Aktuell kann man die Begleiter-App nicht ohne OpenID-Login betreiben, und die Funktion habe ich aktuell nicht in Planung. 

Alternativ könntest du die Desktop-App auch im Netzwerk betreiben, die ist aber nicht mobil-optimiert. 


Melde dich gern, falls du noch weiter Hilfestellung benötigst oder Fragen hast :)
